# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: "1 - [FEAT] Build & PR"

on:
  push:
    branches: 
      - 'feature**'

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    #-----Setup do job-----
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    #-----Setup do job-----
    - run: cd ./app && npm install && npm run build

  test:
    name: Run tests
    runs-on: ubuntu-latest
    
    needs:
      - build

    strategy:
      matrix:
        node-version: [18.x]
        
    steps:
    #-----Setup do job-----
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    #-----Setup do job-----
    - run: cd ./app && npm install && npm run test

  open-pr-to-develop:
    name: Open PR to develop
    runs-on: ubuntu-latest

    needs:
      - build
      - test

    steps:
    - uses: actions/checkout@v3
      name: checkout

    - uses: rlespinasse/git-commit-data-action@v1
      name: extract git commit data

    - name: Extract branch name
      shell: bash
      run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT
      id: extract_branch

    - uses: desbravacloud/action-create-pull-requests@v1
      name: pull-request
      with:
        origin-branch: ${{steps.extract_branch.outputs.branch}}
        target-branch: "develop"
        custom-title: "Pulling ${{ env.GIT_COMMIT_MESSAGE_SUBJECT  }} into develop"
        custom-body: PR gerado automáticamente pela esteira