# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: "1 - [FEAT] Build & PR"

on:
  push:
    branches: 
      - 'feature**'

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    #-----Setup do job-----
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    #-----Setup do job-----
    - run: cd ./app && npm install && npm run build

  test:
    name: Run tests
    runs-on: ubuntu-latest
    
    needs:
      - build

    strategy:
      matrix:
        node-version: [18.x]
        
    steps:
    #-----Setup do job-----
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    #-----Setup do job-----
    - run: cd ./app && npm install && npm run test

  open-pr-to-develop:
    name: Open PR to develop
    runs-on: ubuntu-latest

    needs:
      - build
      - test

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      

    - name: Extracting commit data
      uses: rlespinasse/git-commit-data-action@v1
      
    - name: Create report file
      run: date +%s > report.txt

    - name: Create auto PR
      uses: peter-evans/create-pull-request@v5.0.1
      with:
        branch: "develop"
        title: "PR automatically generated"
        committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
        author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
        body:
          PR automatically generated
        token: ${{ secrets.GITHUB_TOKEN }}