# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: "1 - [FEAT] Build & PR"

on:
  push:
    branches: 
      - 'feature**'

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    #-----Setup do job-----
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    #-----Setup do job-----
    - run: cd ./app && npm install && ng build

  test:
    name: Run tests
    runs-on: ubuntu-latest
    
    needs:
      - build

    strategy:
      matrix:
        node-version: [18.x]
        
    steps:
    #-----Setup do job-----
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    #-----Setup do job-----
    - run: ls -la
    - run: cd ./app && npm install && npm run test && ls -la

  open-pr-to-develop:
    name: Open PR to develop
    runs-on: ubuntu-latest

    needs:
      - build
      - test

    steps:
    - uses: actions/checkout@v3
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "develop"
        pr_title: "Pulling ${{ github.ref }} into develop"
        pr_body: "*An automated PR*"
        github_token: ${{ secrets.GITHUB_TOKEN}}